// Tenant data types
export interface GalleryImage {
  src?: string; // Primary source
  before?: string; // For before/after comparisons
  after?: string; // For before/after comparisons
  alt?: string;
  beforeAlt?: string;
  afterAlt?: string;
  caption?: string;
  width?: number;
  height?: number;
}

export interface TenantReview {
  quote?: string; // Main review text
  text?: string; // Alternative field name
  author?: string;
  location?: string;
  stars?: number;
}

export interface TenantData {
  name: string;
  slug: string;
  phone?: string;
  email?: string;
  address?: string;
  homeUrl?: string;
  logo?: string;
  brand?: {
    primary?: string;
    accent?: string;
  };
  gallery: GalleryImage[];
  reviews: TenantReview[];
  serviceAreas?: string[];
  priceAnchor?: {
    fromText?: string;
    rangeText?: string;
  };
  guarantees?: {
    bullets: string[];
    riskReversal?: string;
  };
  urgencyBanner?: {
    text: string;
    sub?: string;
  };
  leadMagnet?: {
    title: string;
    cta: string;
    url?: string;
  };
}

export interface TenantEnrichment {
  ogImage?: string;
  siteName?: string;
  themeColor?: string;
  phone?: string;
  email?: string;
}

/**
 * Load static tenant data from JSON file
 */
export function getTenantStatic(slug: string): TenantData | null {
  try {
    const data = require(`./${slug}.json`);
    return data as TenantData;
  } catch {
    console.warn(`Tenant data not found for: ${slug}`);
    return null;
  }
}

/**
 * Load tenant gallery override (generated by image import)
 */
export async function getTenantGallery(slug: string): Promise<GalleryImage[]> {
  try {
    const gallery = await import(`./${slug}_gallery.json`);
    return gallery.default || [];
  } catch (error) {
    console.warn(`Gallery not found for tenant: ${slug}`);
    return [];
  }
}

/**
 * Fetch enrichment data from tenant's website via OG tags
 */
export async function getTenantEnrichment(url?: string): Promise<TenantEnrichment> {
  if (!url) return {};

  try {
    const baseUrl = typeof window !== 'undefined' 
      ? window.location.origin 
      : process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:3000';
    
    const response = await fetch(`${baseUrl}/api/tenant-og?url=${encodeURIComponent(url)}`, {
      method: 'GET',
      headers: { 'Content-Type': 'application/json' },
      cache: 'no-store',
    });

    if (!response.ok) return {};

    const data = await response.json();
    return data as TenantEnrichment;
  } catch (error) {
    console.warn('Failed to fetch tenant enrichment:', error);
    return {};
  }
}

/**
 * Deep merge tenant data with enrichment and gallery override
 */
export function mergeTenantData(
  base: TenantData,
  enrichment: TenantEnrichment,
  galleryOverride: GalleryImage[] | null
): TenantData {
  const merged = { ...base };

  // Apply enrichment (enrichment wins where present)
  if (enrichment.siteName && !merged.name) {
    merged.name = enrichment.siteName;
  }

  if (enrichment.themeColor && !merged.brand?.primary) {
    merged.brand = { ...merged.brand, primary: enrichment.themeColor };
  }

  if (enrichment.phone && !merged.phone) {
    merged.phone = enrichment.phone;
  }

  if (enrichment.email && !merged.email) {
    merged.email = enrichment.email;
  }

  // Apply gallery override if present
  if (galleryOverride && galleryOverride.length > 0) {
    merged.gallery = galleryOverride;
  }

  // Add enriched OG image to gallery if not already present
  if (enrichment.ogImage && !merged.gallery.some(img => img.src === enrichment.ogImage)) {
    merged.gallery.unshift({
      src: enrichment.ogImage,
      alt: `${merged.name} - Featured image`,
      caption: 'From our website',
    });
  }

  return merged;
}
