export function normalizeFireDoorFieldLabel(input: string): string {
  const s = String(input || '').trim();
  // Strip wrapping quotes from the one-column "CSV" list.
  const unquoted = s.replace(/^"(.*)"$/, '$1').replace(/^'(.*)'$/, '$1').trim();
  // Normalize repeated whitespace.
  return unquoted.replace(/\s+/g, ' ').trim();
}

const FIRE_DOOR_FIELD_LABELS_RAW = [
  'Name',
  'Sequence',
  'Batch / Phase',
  'Door Ref',
  'Location',
  'Doorset / Leaf  / Frame',
  'Type',
  'Quantity',
  'Fire Rating',
  'Acoustic Rating',
  'Bottom Seal Requirement',
  'Bottom Seal Type',
  'Bottom Seal',
  'Bottom Seal Cost',
  'Bottom Seal Labour',
  'Lead Lining Code',
  'Lead Lining Cost',
  'Lead Lining Labour',
  'Number of Leaves inc solid overpanel',
  'Leaf Configuration',
  'If split, Master leaf size',
  'Action',
  'Handing',
  'Hinge Supply Type',
  'Hinge Qty',
  'Hinge Type',
  'Hinge Cost',
  'Hinge Labour',
  'Hinge Configuration',
  'Lock Prep',
  'Lock Supply Type',
  'Lock Type 1',
  'Lock Type 1 Cost',
  'Lock Type 1 Labour',
  'Lock Height',
  'Spindle face prep',
  'Spindle face prep Labour',
  'Cylinder Face Prep',
  'Cylinder Face Prep Labour',
  'Lock Type 2',
  'Lock Type 2 Cost',
  'Lock Type 2 Labour',
  'Lock Height 2',
  'Spindle face prep - Lock 2',
  'Spindle face prep - Lock 2 Labour',
  'Cylinder Face Prep - Lock 2',
  'Cylinder Face Prep - Lock 2 Labour',
  'Flush Bolt Supply/prep',
  'Flush Bolt Cost',
  'Flush Bolt Labour',
  'Flush bolt qty',
  'Levers & pull handles',
  'Levers & pull handles Cost',
  'Levers & pull handles Labour',
  'Escutcheons/bathroom turn',
  'Escutcheons/bathroom turn Cost',
  'Escutcheons/bathroom turn Labour',
  'Cylinder Lock 1',
  'Cylinder Lock 1 Cost',
  'Cylinder Lock 1 Labour',
  'Cylinder lock 2',
  'Cylinder Lock 2 Cost',
  'Cylinder Lock 2 Labour',
  'Finger Plates',
  'Finger Plates Cost',
  'Finger Plates Labour',
  'Kick Plates',
  'Kick Plates Cost',
  'Kick Plates Labour',
  'Kick plate position',
  'Bump Plate',
  'Bump Plate Cost',
  'Bump Plate Labour',
  'Fire Signage',
  'Fire Signage Cost',
  'Fire Signage Labour',
  'Additional signage',
  'Additional signage Cost',
  'Additional signage Labour',
  'Letter Plate',
  'Letter Plate Cost',
  'Letter Plate Labour',
  'Letter plate position',
  'Door viewer',
  'Door viewer Cost',
  'Door viewer Labour',
  'Door viewer position',
  'Door viewer hole prep size',
  'Door Chain',
  'Door Chain Cost',
  'Door Chain Labour',
  'Finger Protection',
  'Finger Protection Cost',
  'Finger Protection Labour',
  'Fire ID Disc',
  'Fire ID Disc Cost',
  'Fire ID Disc Labour',
  'Factory Fit Hinges',
  'Factory Fit Hinges Labour',
  'Factory Fit Locks',
  'Factory Fit Locks Labour',
  'Factory Fit Flush Bolts',
  'Factory Fit Flush Bolts Labour',
  'Ironmongery Pack REF',
  'Comments',
  'Closer type',
  'Closers/floorsprings',
  'Closers/floorsprings Cost',
  'Closers/floorsprings Labour',
  'anti barricade / emergency stop',
  'anti barricade / emergency stop Cost',
  'anti barricade / emergency stop Labour',
  'Wiring prep',
  'Wiring prep Labour',
  'Cable loop',
  'Cable loop Cost',
  'Cable loop Labour',
  'Addition 1 / Note 1',
  'Addition 1 Qty',
  'Addition 2 / Note 2',
  'Addition 2 Qty',
  'Addition 3 / Note 3',
  'Addition 3 Qty',
  'S/O Width',
  'S/O Height',
  'S/O Wall thickness',
  'Extension Material',
  'Extension Material Cost',
  'Extension Material Labour',
  'Extension lining width visible',
  'Extension lining width actual size',
  'Overpanel details',
  'Screen details',
  'Fanlight / Overpanel Qty',
  'Fanlight / Overpanel Qty Cost',
  'Fanlight / Overpanel Qty Labour',
  'Fanlight Frame Thickness (Production)',
  'Fanlight / Overpanel height',
  'Fanlight / Overpanel Width',
  'Number of Sidelight 1',
  'Number of Sidelight 1 Cost',
  'Number of Sidelight 1 Labour',
  'Sidelight 1 Width',
  'Sidelight 1 Height',
  'Number of Sidelight 2',
  'Number of Sidelight 2 Cost',
  'Number of Sidelight 2 Labour',
  'Sidelight 2 Width',
  'Sidelight 2 Height',
  'Number of Sidelight 3',
  'Number of Sidelight 3 Cost',
  'Number of Sidelight 3 Labour',
  'Sidelight 3 Width',
  'Sidelight 3 Height',
  'Number of Sidelight 4',
  'Number of Sidelight 4 Cost',
  'Number of Sidelight 4 Labour',
  'Sidelight 4 Width',
  'Sidelight 4 Height',
  'Fanlight / Sidelight Glazing',
  'Fanlight / Sidelight Glazing Cost',
  'Fanlight / Sidelight Glazing Labour',
  'O/F Width (doorset)',
  'O/F Height (doorset)',
  'Frame Thickness',
  'Frame Material',
  'Frame Material (Production)',
  'Lining Thickness - Jambs',
  'Lining Cost',
  'Lining Labour',
  'Jamb Profile - Hanging Edge',
  'Jamb Profile - Leading Edge Edge',
  'Jamb Cost',
  'Jamb Labour',
  'Lining Thickness - Heads',
  'Frame Finish',
  'Frame Type',
  'Stop Material',
  'Stop Cost',
  'Stop Labour',
  'Stop Material (Production)',
  'Rebate / Stop Width',
  'Rebate / Stop Depth',
  'Arc Material',
  'Arc Stop',
  'Arc Labour',
  'Arc Detail',
  'Arc Width',
  'Arc Depth',
  'M Leaf Width',
  'S Leaf Width',
  'Leaf Height',
  'Leaf Thickness',
  'Core Type',
  'Leaf Style',
  'Leaf Cost',
  'Leaf Labour',
  'Vision Panel Qty, Leaf 1',
  'Vision Panel 1 Cost',
  'Vision Panel 1 Labour',
  'Leaf Aperture 1 Width',
  'Leaf Aperture 1 Height',
  'Leaf Aperture 1 Width (Production)',
  'Leaf Aperture 1 Height (Production)',
  'Aperture Position 1',
  'Vision Panel Leaf 1 Aperture 2 Cost',
  'Vision Panel Leaf 1 Aperture 2 Labour',
  'Leaf 1 Aperture 2 Width',
  'Leaf 1 Aperture 2 Height',
  'Leaf 1 Aperture 2 Width (Production)',
  'Leaf 1 Aperture 2 Height (Production)',
  'Aperture Position 2',
  'Air Transfer grille requirement',
  'Air Transfer Grille Qty',
  'Air Transfer grille Size',
  'Air Transfer grille Position',
  'Vision Panel Qty, Leaf 2',
  'Vision Panel Leaf 2 Aperture 1 Cost',
  'Vision Panel Leaf 2 Aperture 1 Labour',
  'Leaf 2 Cutout Aperture 1 Width',
  'Leaf 2 Cutout Aperture 1 Height',
  'Leaf 2 Aperture 1 Width (Production)',
  'Leaf 2 Aperture 1 Height (Production)',
  'Vision Panel Leaf 2 Aperture 2 Cost',
  'Vision Panel Leaf 2 Aperture 2 Labour',
  'Leaf 2 Cutout Aperture 2 Width',
  'Leaf 2 Cutout Aperture 2 Height',
  'Leaf 2 Aperture 2 Width (Production)',
  'Leaf 2 Aperture 2 Height (Production)',
  'Vision Panel Size Detail',
  'Temp Glass Check',
  'Glass Concat',
  'Glass Type',
  'Bead Type',
  'Bead Material',
  'Bead Material (Production)',
  'Total Glazed Area Master Leaf (msq)',
  'Glazing Tape',
  'Glazing Tape Cost',
  'Glazing Tape Labour',
  'Max Permitted Glazed Area (Based on Strebord)',
  'Door Facing',
  'Door Finish - Side 1 (Push)',
  'Door Finish - Side 1 (Push) Cost',
  'Door Finish - Side 1 (Push) Labour',
  'Door Finish - Side 2 (Pull)',
  'Door Finish - Side 2 (Pull) Cost',
  'Door Finish - Side 2 (Pull) Labour',
  'Door Colour',
  'Lipping Material',
  'Lipping Cost',
  'Lipping Labour',
  'Lipping Material (Production)',
  'Lipping Style',
  'Lipping Thickness',
  'Lipping Finish',
  'Door Edge Protection Type',
  'Door Edge Protection Type Cost',
  'Door Edge Protection Type Labour',
  'Door Edge Protection Position',
  'PVC Face Protection',
  'PVC Face Protection Cost',
  'PVC Face Protection Labour',
  'PVC Colour',
  'PVC Cost',
  'PVC Labour',
  'Door Undercut',
  'Certification',
  'Q Mark Plug Outer Colour',
  'Q Mark Tree Colour',
  'Q Mark Vision Panel Plug',
  'Material Sustainability',
  'Cost Of Materials',
  'Cost Of Labour',
  'Line Cost',
  'Line Sell',
  'Price Ea',
  'Qty2',
  'Line Price',
  'Important notes for Fire Rating',
  'Client Notes 1',
  'Client Notes 2',
  'Client Notes 3',
  'Client Notes 4',
  'Test Certificate Used',
  'Associated Document',
  'Master Leaf Weight (Approx) kg',
  'Fire Rating2',
  'Latched/Unlatched',
  'Single Action / Double Action',
  'Single Door / Double Door',
  'Door Leaf Type',
  'Wizardoorer Ref (If used)',
  'Master Leaf Area',
  'Slave Leaf Area',
  'Leaf Weight Code',
  'Leaf Weight msq',
  'Slave Leaf Weight (Approx) kg',
  'Lining Volume',
  'Lining Material',
  'Lining Material Weight msq',
  'Lining Weight (Approx) kg',
  'Stop Volume',
  'Stop Material2',
  'Stop Material Density',
  'Stop Weight (Approx) kg',
  'Arc Volume',
  'Arc Material3',
  'Arc Material Density',
  'Arc Weight (Approx) kg',
  'Fanlight',
  'Screen',
  'Frame Weight (Approx) kg',
  'Doorset Weight (Approx) kg - Ironmongery not allowed for',
] as const;

export const FIRE_DOOR_FIELD_LABELS: readonly string[] = (() => {
  const out: string[] = [];
  const seen = new Set<string>();
  for (const raw of FIRE_DOOR_FIELD_LABELS_RAW) {
    const label = normalizeFireDoorFieldLabel(raw);
    if (!label) continue;
    const norm = label.toLowerCase();
    if (seen.has(norm)) continue;
    seen.add(norm);
    out.push(label);
  }
  return out;
})();

export function isCostOrLabourFieldLabel(label: string): boolean {
  const l = normalizeFireDoorFieldLabel(label).toLowerCase();
  return l.endsWith(' cost') || l.endsWith(' labour') || l.endsWith('cost') || l.endsWith('labour');
}

export const FIRE_DOOR_MATCHABLE_FIELD_LABELS: readonly string[] = FIRE_DOOR_FIELD_LABELS.filter(
  (l) => !isCostOrLabourFieldLabel(l)
);
