import { normalizeFireDoorFieldLabel } from './fieldCatalog';

// Maps Fire Door spreadsheet *column labels* to the corresponding DB column name.
//
// - Keys are normalized (lowercased) labels.
// - Values are Prisma `FireDoorLineItem` scalar field names.
// - UI-only column keys that alias to DB fields are already resolved here.
export const FIRE_DOOR_DB_KEY_BY_LABEL: Readonly<Record<string, string>> = {
  "#": "rowIndex",
  "acoustic rating": "acousticRatingDb",
  "action": "action",
  "addition 1 / note 1": "additionNote1",
  "addition 1 qty": "additionNote1Qty",
  "addition 2 / note 2": "addition2",
  "addition 2 qty": "addition2Qty",
  "addition 3 / note 3": "addition3",
  "addition 3 qty": "addition3Qty",
  "additional signage": "additionalSignage",
  "air transfer grille position": "airTransferGrillePosition",
  "air transfer grille qty": "airTransferGrilleQty",
  "air transfer grille requirement": "airTransferGrilleReq",
  "air transfer grille size": "airTransferGrilleSize",
  "anti barricade / emergency stop": "antiBarricade",
  "aperture position 1": "aperturePosition1",
  "aperture position 2": "aperturePosition2",
  "arc depth": "arcDepth",
  "arc detail": "arcDetail",
  "arc material": "arcMaterial",
  "arc material density": "arcMaterialDensity",
  "arc material3": "arcMaterial3",
  "arc volume": "arcVolume",
  "arc weight (approx) kg": "arcWeight",
  "arc width": "arcWidth",
  "associated document": "associatedDocument",
  "batch / phase": "batchPhase",
  "bead material": "beadMaterial",
  "bead material (production)": "beadMaterialProduction",
  "bead type": "beadType",
  "bottom seal requirement": "bottomSealReq",
  "bottom seal type": "bottomSealType",
  "bump plate": "bumpPlate",
  "cable loop": "cableLoop",
  "certification": "certification",
  "client notes 1": "clientNotes1",
  "client notes 2": "clientNotes2",
  "client notes 3": "clientNotes3",
  "client notes 4": "clientNotes4",
  "closer type": "closerOrFloorSpring",
  "closers/floorsprings": "closerOrFloorSpring",
  "comments": "comments",
  "core type": "coreType",
  "cylinder face prep": "cylinderFacePrep",
  "cylinder face prep - lock 2": "cylinderFacePrep2",
  "cylinder lock 1": "cylinderLock1",
  "cylinder lock 2": "cylinderLock2",
  "door chain": "doorChain",
  "door colour": "doorColour",
  "door edge protection position": "doorEdgeProtPos",
  "door edge protection type": "doorEdgeProtType",
  "door facing": "doorFacing",
  "door finish - side 1 (push)": "doorFinishSide1",
  "door finish - side 2 (pull)": "doorFinishSide2",
  "door leaf type": "doorLeafType",
  "door ref": "doorRef",
  "door ref7": "doorRef7",
  "door undercut": "doorUndercut",
  "door viewer": "doorViewer",
  "door viewer hole prep size": "doorViewerPrepSize",
  "door viewer position": "doorViewerPosition",
  "doorset / leaf / frame": "doorsetType",
  "doorset weight (approx) kg - ironmongery not allowed for": "doorsetWeight",
  "escutcheons/bathroom turn": "escutcheons",
  "extension lining width actual size": "extensionLiningWidthActual",
  "extension lining width visible": "extensionLiningWidthVisible",
  "extension material": "extensionMaterial",
  "factory fit flush bolts": "factoryFitFlushBolts",
  "factory fit hinges": "factoryFitHinges",
  "factory fit locks": "factoryFitLocks",
  "fanlight": "fanlight",
  "fanlight / overpanel height": "fanlightOverpanelHeight",
  "fanlight / overpanel qty": "fanlightOverpanelQty",
  "fanlight / overpanel width": "fanlightOverpanelWidth",
  "fanlight / sidelight glazing": "fanlightSidelightGlz",
  "fanlight frame thickness (production)": "fanlightFrameThickness",
  "finger plates": "fingerPlates",
  "finger protection": "fingerProtection",
  "fire id disc": "fireIdDisc",
  "fire rating": "rating",
  "fire rating2": "fireRating2",
  "fire signage": "fireSignage",
  "flush bolt qty": "flushBoltQty",
  "flush bolt supply/prep": "flushBoltSupplyPrep",
  "frame finish": "frameFinish",
  "frame material": "frameMaterial",
  "frame material (production)": "frameMaterialProduction",
  "frame thickness": "frameThickness",
  "frame type": "frameType",
  "frame weight (approx) kg": "frameWeight",
  "glass concat": "glassConcat",
  "glass type": "glassType",
  "glazing tape": "glazingTape",
  "handing": "handing",
  "hinge configuration": "hingeConfiguration",
  "hinge qty": "hingeQty",
  "hinge supply type": "hingeSupplyType",
  "hinge type": "hingeType",
  "if split, master leaf size": "ifSplitMasterSize",
  "important notes for fire rating": "importantNotes",
  "ironmongery pack ref": "ironmongeryPackRef",
  "jamb profile - hanging edge": "jambProfileHanging",
  "jamb profile - leading edge edge": "jambProfileLeading",
  "kick plate position": "kickPlatePosition",
  "kick plates": "kickPlates",
  "latched/unlatched": "latchedUnlatched",
  "lead lining code": "leadLiningCode",
  "name": "code",
  "leaf 1 aperture 2 height": "vp2HeightLeaf1",
  "leaf 1 aperture 2 height (production)": "leaf1Aperture2HeightProduction",
  "leaf 1 aperture 2 width": "vp2WidthLeaf1",
  "leaf 1 aperture 2 width (production)": "leaf1Aperture2WidthProduction",
  "leaf 2 aperture 1 height (production)": "leaf2Aperture1HeightProduction",
  "leaf 2 aperture 1 width (production)": "leaf2Aperture1WidthProduction",
  "leaf 2 aperture 2 height (production)": "leaf2Aperture2HeightProduction",
  "leaf 2 aperture 2 width (production)": "leaf2Aperture2WidthProduction",
  "leaf 2 cutout aperture 1 height": "vp1HeightLeaf2",
  "leaf 2 cutout aperture 1 width": "vp1WidthLeaf2",
  "leaf 2 cutout aperture 2 height": "vp2HeightLeaf2",
  "leaf 2 cutout aperture 2 width": "vp2WidthLeaf2",
  "leaf aperture 1 height": "vp1HeightLeaf1",
  "leaf aperture 1 height (production)": "leaf1Aperture1HeightProduction",
  "leaf aperture 1 width": "vp1WidthLeaf1",
  "leaf aperture 1 width (production)": "leaf1Aperture1WidthProduction",
  "leaf concat": "leafConcat",
  "leaf configuration": "leafConfiguration",
  "leaf height": "leafHeight",
  "leaf style": "leafStyle",
  "leaf thickness": "leafThickness",
  "leaf weight code": "leafWeightCode",
  "leaf weight msq": "leafWeightMsq",
  "letter plate": "letterPlate",
  "letter plate position": "letterPlatePosition",
  "levers & pull handles": "leversHandles",
  "line price": "lineTotal",
  "lining material": "liningMaterial",
  "lining material weight msq": "liningMaterialWeightMsq",
  "lining thickness - heads": "liningThicknessHeads",
  "lining thickness - jambs": "liningThicknessJambs",
  "lining volume": "liningVolume",
  "lining weight (approx) kg": "liningWeight",
  "lipping finish": "lippingFinish",
  "lipping material": "lippingMaterial",
  "lipping material (production)": "lippingMaterialProduction",
  "lipping style": "lippingStyle",
  "lipping thickness": "lippingThickness",
  "location": "location",
  "lock height": "lockHeight",
  "lock height 2": "lockHeight2",
  "lock prep": "lockPrep",
  "lock supply type": "lockSupplyType",
  "lock type 1": "lockType1",
  "lock type 2": "lockType2",
  "m leaf width": "masterLeafWidth",
  "master leaf area": "masterLeafArea",
  "master leaf weight (approx) kg": "masterLeafWeight",
  "material sustainability": "materialSustainability",
  "max permitted glazed area (based on strebord)": "maxPermittedGlazedArea",
  "number of leaves inc solid overpanel": "numLeavesIncOverpanel",
  "number of sidelight 1": "numSidelight1",
  "number of sidelight 2": "numSidelight2",
  "number of sidelight 3": "numSidelight3",
  "number of sidelight 4": "numSidelight4",
  "o/f height (doorset)": "ofHeightDoorset",
  "o/f width (doorset)": "ofWidthDoorset",
  "overpanel details": "overpanelDetails",
  "price ea": "unitValue",
  "pvc colour": "pvcColour",
  "pvc face protection": "pvcFaceProtection",
  "q mark plug outer colour": "qMarkPlugOuterColour",
  "q mark tree colour": "qMarkTreeColour",
  "q mark vision panel plug": "qMarkVisionPanelPlug",
  "qty2": "qty2",
  "quantity": "quantity",
  "rebate / stop depth": "rebateStopDepth",
  "rebate / stop width": "rebateStopWidth",
  "s leaf width": "slaveLeafWidth",
  "s/o height": "soHeight",
  "s/o wall thickness": "soWallThickness",
  "s/o width": "soWidth",
  "screen": "screen",
  "screen details": "screenDetails",
  "sequence": "sequence",
  "sidelight 1 height": "sidelight1Height",
  "sidelight 1 width": "sidelight1Width",
  "sidelight 2 height": "sidelight2Height",
  "sidelight 2 width": "sidelight2Width",
  "sidelight 3 height": "sidelight3Height",
  "sidelight 3 width": "sidelight3Width",
  "sidelight 4 height": "sidelight4Height",
  "sidelight 4 width": "sidelight4Width",
  "single action / double action": "singleDoubleAction",
  "single door / double door": "singleDoubleDoor",
  "slave leaf area": "slaveLeafArea",
  "slave leaf weight (approx) kg": "slaveLeafWeight",
  "spindle face prep": "spindleFacePrep",
  "spindle face prep - lock 2": "spindleFacePrep2",
  "stop material": "stopMaterial",
  "stop material (production)": "stopMaterialProduction",
  "stop material density": "stopMaterialDensity",
  "stop material2": "stopMaterial2",
  "stop volume": "stopVolume",
  "stop weight (approx) kg": "stopWeight",
  "temp glass check": "tempGlassCheck",
  "test certificate used": "testCertificateUsed",
  "total glazed area master leaf (msq)": "totalGlazedAreaMaster",
  "type": "type",
  "vision panel qty, leaf 1": "visionQtyLeaf1",
  "vision panel qty, leaf 2": "visionQtyLeaf2",
  "vision panel size detail": "visionPanelSizeDetail",
  "wiring prep": "wiringPrep",
  "wizardoorer ref (if used)": "wizardoorerRef"
};

function autoDbKeyFromLabel(label: string): string {
  const cleaned = normalizeFireDoorFieldLabel(label)
    .replace(/\u00a0/g, ' ')
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim();

  const parts = cleaned.split(/\s+/).filter(Boolean);
  if (!parts.length) return 'field';

  const [first, ...rest] = parts;
  return first.toLowerCase() + rest.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join('');
}

export function resolveFireDoorDbKeyForLabel(label: string): string {
  const norm = normalizeFireDoorFieldLabel(label).toLowerCase();
  return FIRE_DOOR_DB_KEY_BY_LABEL[norm] ?? autoDbKeyFromLabel(label);
}
