// api/src/lib/standardQuestionnaireFields.ts
/**
 * Standard questionnaire fields for ML training consistency
 * These fields are automatically created for all tenants and provide
 * a consistent feature set for the RandomForest price prediction model.
 * 
 * Updated based on joineryai_questionnaire_fields.csv requirements
 */

export type StandardFieldDefinition = {
  key: string;
  label: string;
  type: "TEXT" | "NUMBER" | "SELECT" | "BOOLEAN" | "TEXTAREA" | "DATE";
  options?: string[];
  required: boolean;
  costingInputKey?: string;
  helpText?: string;
  placeholder?: string;
  sortOrder: number;
  group?: string;
  scope: "client" | "public" | "internal" | "manufacturing";
  isStandard: true;
};

/**
 * Standard fields organized by category
 * These map directly to ML model features and business processes
 */
export const STANDARD_FIELDS: StandardFieldDefinition[] = [
  // ============ CLIENT PROFILE (scope: client) ============
  {
    key: "installation_required",
    label: "Installation Required",
    type: "BOOLEAN",
    required: false,
    costingInputKey: "installation_required",
    helpText: "Professional installation needed?",
    sortOrder: 100,
    group: "Client Profile",
    scope: "client",
    isStandard: true,
  },
  {
    key: "contact_name",
    label: "Your Name",
    type: "TEXT",
    required: true,
    helpText: "Full name for correspondence",
    placeholder: "John Smith",
    sortOrder: 101,
    group: "Client Profile",
    scope: "client",
    isStandard: true,
  },
  {
    key: "company",
    label: "Company",
    type: "TEXT",
    required: false,
    helpText: "Company name if applicable",
    placeholder: "ABC Builders Ltd",
    sortOrder: 102,
    group: "Client Profile",
    scope: "client",
    isStandard: true,
  },
  {
    key: "email",
    label: "Email Address",
    type: "TEXT",
    required: true,
    helpText: "We'll send your quote to this email",
    placeholder: "john@example.com",
    sortOrder: 103,
    group: "Client Profile",
    scope: "client",
    isStandard: true,
  },
  {
    key: "phone",
    label: "Phone Number",
    type: "TEXT",
    required: false,
    helpText: "Optional contact number",
    placeholder: "07700 900000",
    sortOrder: 104,
    group: "Client Profile",
    scope: "client",
    isStandard: true,
  },
  {
    key: "lead_source",
    label: "How did you hear about us?",
    type: "SELECT",
    options: ["Website", "Google Search", "Referral", "Social Media", "Advertisement", "Previous Customer", "Other"],
    required: false,
    costingInputKey: "lead_source",
    helpText: "Marketing attribution",
    sortOrder: 105,
    group: "Client Profile",
    scope: "client",
    isStandard: true,
  },
  {
    key: "region",
    label: "Project Location",
    type: "SELECT",
    options: ["London", "South East", "South West", "Midlands", "North West", "North East", "Yorkshire", "Scotland", "Wales", "Northern Ireland", "Channel Islands", "Other"],
    required: false,
    costingInputKey: "region",
    helpText: "Geographic location affects delivery and installation costs",
    sortOrder: 106,
    group: "Client Profile",
    scope: "client",
    isStandard: true,
  },
  {
    key: "timeframe",
    label: "Project Timeframe",
    type: "SELECT",
    options: ["ASAP (within 1 month)", "1-2 months", "3-6 months", "6+ months", "Flexible"],
    required: false,
    helpText: "When do you need completion?",
    sortOrder: 107,
    group: "Client Profile",
    scope: "client",
    isStandard: true,
  },
  {
    key: "property_listed",
    label: "Listed Building",
    type: "SELECT",
    options: ["Yes", "No", "Not Sure"],
    required: false,
    costingInputKey: "property_listed",
    helpText: "Special considerations if listed",
    sortOrder: 108,
    group: "Client Profile",
    scope: "client",
    isStandard: true,
  },
  {
    key: "budget_range",
    label: "Budget Range",
    type: "SELECT",
    options: ["Under £5,000", "£5,000 - £15,000", "£15,000 - £30,000", "£30,000 - £50,000", "Over £50,000", "Not sure yet"],
    required: false,
    helpText: "Approximate spend guideline",
    sortOrder: 109,
    group: "Client Profile",
    scope: "client",
    isStandard: true,
  },
  {
    key: "additional_notes",
    label: "Additional Details",
    type: "TEXTAREA",
    required: false,
    helpText: "Any other info to help quoting",
    placeholder: "Specific requirements, existing issues…",
    sortOrder: 110,
    group: "Client Profile",
    scope: "client",
    isStandard: true,
  },
  {
    key: "new_build_existing",
    label: "New build/Existing",
    type: "SELECT",
    options: ["New Build", "Existing Property", "Renovation"],
    required: false,
    helpText: "Type of property",
    sortOrder: 111,
    group: "Client Profile",
    scope: "client",
    isStandard: true,
  },

  // ============ PUBLIC QUESTIONNAIRE (scope: public - customer-facing) ============
  {
    key: "glazing_type",
    label: "Glazing Type",
    type: "SELECT",
    options: ["Standard Double Glazing", "Triple Glazing", "Vacuum Glass", "Single Glazing", "None"],
    required: false,
    costingInputKey: "glazing_type",
    helpText: "Glass specification",
    sortOrder: 200,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "has_curves",
    label: "Curved or Arched Design",
    type: "BOOLEAN",
    required: false,
    costingInputKey: "has_curves",
    helpText: "Includes curved or arched elements",
    sortOrder: 201,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "window_style",
    label: "Window Style",
    type: "SELECT",
    options: ["Casement", "Sash", "Tilt & Turn", "Fixed", "Bay", "Other"],
    required: false,
    helpText: "Window opening style",
    sortOrder: 202,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "door_type",
    label: "Door Type",
    type: "SELECT",
    options: ["External Front Door", "Internal Door", "Bifold Doors", "French Doors", "Sliding Doors", "Stable Door"],
    required: false,
    costingInputKey: "door_type",
    helpText: "Primary door type",
    sortOrder: 203,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "timber_type",
    label: "Timber Type",
    type: "SELECT",
    options: ["Oak", "Accoya", "Iroko", "Sapele", "Pine", "Engineered", "Other"],
    required: false,
    costingInputKey: "timber_type",
    helpText: "Wood species",
    sortOrder: 204,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "finish",
    label: "Finish",
    type: "SELECT",
    options: ["Factory Painted", "Factory Stained", "Primed Only", "Bare Wood"],
    required: false,
    costingInputKey: "finish",
    helpText: "Surface finish",
    sortOrder: 205,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "ironmongery_level",
    label: "Ironmongery Level",
    type: "SELECT",
    options: ["Standard", "Enhanced", "Heritage"],
    required: false,
    costingInputKey: "ironmongery_level",
    helpText: "Quality / complexity of ironmongery",
    sortOrder: 206,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "ironmongery_description",
    label: "Ironmongery Description",
    type: "TEXTAREA",
    required: false,
    helpText: "Specific ironmongery requirements",
    placeholder: "e.g., Brass handles, security locks...",
    sortOrder: 207,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "quantity",
    label: "Quantity",
    type: "NUMBER",
    required: false,
    costingInputKey: "quantity",
    helpText: "Total count of identical items",
    placeholder: "e.g., 2",
    sortOrder: 208,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "preferred_installation_date",
    label: "Preferred Installation Date",
    type: "DATE",
    required: false,
    helpText: "When would you like installation?",
    sortOrder: 209,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "project_description",
    label: "Project Description",
    type: "TEXTAREA",
    required: false,
    helpText: "Brief description of what you need",
    placeholder: "Tell us about your project...",
    sortOrder: 210,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "height_mm",
    label: "Height (mm)",
    type: "NUMBER",
    required: false,
    costingInputKey: "height_mm",
    helpText: "Height in millimeters",
    placeholder: "e.g., 2100",
    sortOrder: 211,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "width_mm",
    label: "Width (mm)",
    type: "NUMBER",
    required: false,
    costingInputKey: "width_mm",
    helpText: "Width in millimeters",
    placeholder: "e.g., 900",
    sortOrder: 212,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "glazing_bars",
    label: "Glazing Bars",
    type: "BOOLEAN",
    required: false,
    costingInputKey: "glazing_bars",
    helpText: "Include glazing bars in windows/doors",
    sortOrder: 213,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },

  // ============ INTERNAL (scope: internal - backend only) ============
  {
    key: "area_m2",
    label: "Project Area (m²)",
    type: "NUMBER",
    required: true,
    costingInputKey: "area_m2",
    helpText: "Computed automatically from dimensions",
    sortOrder: 300,
    group: "Internal",
    scope: "internal",
    isStandard: true,
  },
  {
    key: "project_type",
    label: "Project Type",
    type: "SELECT",
    options: ["Windows", "Doors", "French Doors", "Bifold Doors", "Sash Windows", "Staircase", "Kitchen", "Wardrobes", "Alcove Units", "Other"],
    required: true,
    costingInputKey: "project_type",
    helpText: "Set by tenant – internal classification",
    sortOrder: 301,
    group: "Internal",
    scope: "internal",
    isStandard: true,
  },
  {
    key: "date_quote_sent",
    label: "Date Quote Sent",
    type: "DATE",
    required: false,
    helpText: "Auto-populated when quote sent",
    sortOrder: 302,
    group: "Internal",
    scope: "internal",
    isStandard: true,
  },
  {
    key: "quoted_by",
    label: "Quoted by",
    type: "SELECT",
    options: ["Sales Team", "Director", "Workshop Manager", "Admin"],
    required: false,
    helpText: "Who prepared the quote",
    sortOrder: 303,
    group: "Internal",
    scope: "internal",
    isStandard: true,
  },
  {
    key: "date_of_enquiry",
    label: "Date of Enquiry",
    type: "DATE",
    required: false,
    helpText: "Auto-populated when lead created",
    sortOrder: 304,
    group: "Internal",
    scope: "internal",
    isStandard: true,
  },
  {
    key: "quote_ref",
    label: "Quote ref",
    type: "TEXT",
    required: false,
    helpText: "Internal reference number",
    placeholder: "e.g., Q-2025-001",
    sortOrder: 305,
    group: "Internal",
    scope: "internal",
    isStandard: true,
  },
  {
    key: "quote_value",
    label: "Quote Value",
    type: "NUMBER",
    required: false,
    helpText: "Total quoted amount",
    sortOrder: 306,
    group: "Internal",
    scope: "internal",
    isStandard: true,
  },
  {
    key: "source",
    label: "Source",
    type: "SELECT",
    options: ["Website", "Phone", "Email", "Walk-in", "Referral", "Trade", "Other"],
    required: false,
    helpText: "Lead origin channel",
    sortOrder: 307,
    group: "Internal",
    scope: "internal",
    isStandard: true,
  },
  {
    key: "timber",
    label: "Timber",
    type: "SELECT",
    options: ["Oak", "Accoya", "Iroko", "Sapele", "Pine", "Engineered", "Mixed", "Other"],
    required: false,
    helpText: "Timber specification for internal tracking",
    sortOrder: 308,
    group: "Internal",
    scope: "internal",
    isStandard: true,
  },
  {
    key: "site_visit_required",
    label: "Site Visit Required?",
    type: "BOOLEAN",
    required: false,
    helpText: "Needs on-site survey",
    sortOrder: 309,
    group: "Internal",
    scope: "internal",
    isStandard: true,
  },
  {
    key: "date_order_placed",
    label: "Date Order Placed",
    type: "DATE",
    required: false,
    helpText: "Auto-populated when opportunity won",
    sortOrder: 310,
    group: "Internal",
    scope: "internal",
    isStandard: true,
  },

  // ============ MANUFACTURING (scope: manufacturing - post-won production) ============
  {
    key: "production_notes",
    label: "Production Notes",
    type: "TEXTAREA",
    required: false,
    helpText: "Special instructions for manufacturing",
    placeholder: "Any specific details for workshop...",
    sortOrder: 400,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "manufacturing_start_date",
    label: "Manufacturing Start Date",
    type: "DATE",
    required: false,
    helpText: "When manufacturing/production begins",
    sortOrder: 401,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "manufacturing_end_date",
    label: "Manufacturing End Date",
    type: "DATE",
    required: false,
    helpText: "When manufacturing/production completes",
    sortOrder: 402,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "installation_start_date",
    label: "Installation Start Date",
    type: "DATE",
    required: false,
    helpText: "When installation begins",
    sortOrder: 403,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "installation_end_date",
    label: "Installation End Date",
    type: "DATE",
    required: false,
    helpText: "When installation completes",
    sortOrder: 404,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  // Material tracking - Timber
  {
    key: "timber_ordered",
    label: "Timber - Ordered",
    type: "DATE",
    required: false,
    helpText: "Date timber was ordered",
    sortOrder: 405,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "timber_expected",
    label: "Timber - Expected",
    type: "DATE",
    required: false,
    helpText: "Expected timber delivery date",
    sortOrder: 406,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "timber_received",
    label: "Timber - Received",
    type: "DATE",
    required: false,
    helpText: "Date timber was received",
    sortOrder: 407,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  // Material tracking - Glass
  {
    key: "glass_ordered",
    label: "Glass - Ordered",
    type: "DATE",
    required: false,
    helpText: "Date glass was ordered",
    sortOrder: 408,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "glass_expected",
    label: "Glass - Expected",
    type: "DATE",
    required: false,
    helpText: "Expected glass delivery date",
    sortOrder: 409,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "glass_received",
    label: "Glass - Received",
    type: "DATE",
    required: false,
    helpText: "Date glass was received",
    sortOrder: 410,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  // Material tracking - Ironmongery
  {
    key: "ironmongery_ordered",
    label: "Ironmongery - Ordered",
    type: "DATE",
    required: false,
    helpText: "Date ironmongery was ordered",
    sortOrder: 411,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "ironmongery_expected",
    label: "Ironmongery - Expected",
    type: "DATE",
    required: false,
    helpText: "Expected ironmongery delivery date",
    sortOrder: 412,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "ironmongery_received",
    label: "Ironmongery - Received",
    type: "DATE",
    required: false,
    helpText: "Date ironmongery was received",
    sortOrder: 413,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  // Material tracking - Paint
  {
    key: "paint_ordered",
    label: "Paint - Ordered",
    type: "DATE",
    required: false,
    helpText: "Date paint was ordered",
    sortOrder: 414,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "paint_expected",
    label: "Paint - Expected",
    type: "DATE",
    required: false,
    helpText: "Expected paint delivery date",
    sortOrder: 415,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "paint_received",
    label: "Paint - Received",
    type: "DATE",
    required: false,
    helpText: "Date paint was received",
    sortOrder: 416,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  // Production planning
  {
    key: "projected_hours",
    label: "Projected Hours",
    type: "NUMBER",
    required: false,
    helpText: "Estimated production time",
    placeholder: "e.g., 40",
    sortOrder: 417,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "signed_off_date",
    label: "Signed Off Date",
    type: "DATE",
    required: false,
    helpText: "Date work was approved/completed",
    sortOrder: 418,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "fensa_registration",
    label: "FENSA Registration",
    type: "BOOLEAN",
    required: false,
    helpText: "FENSA certification required",
    sortOrder: 419,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
];

/**
 * Get fields by group for conditional rendering
 */
export function getFieldsByGroup(group: string): StandardFieldDefinition[] {
  return STANDARD_FIELDS.filter((f) => f.group === group);
}

/**
 * Get all unique groups in display order
 */
export function getFieldGroups(): string[] {
  const groups = [...new Set(STANDARD_FIELDS.map((f) => f.group).filter(Boolean))];
  const order = ["Client Profile", "Public Questionnaire", "Internal", "Manufacturing"];
  return order.filter((g) => groups.includes(g));
}

/**
 * Get fields by scope for context-specific rendering
 */
export function getFieldsByScope(scope: "client" | "public" | "internal" | "manufacturing"): StandardFieldDefinition[] {
  return STANDARD_FIELDS.filter((f) => f.scope === scope);
}

/**
 * Get fields that map to ML features (have costingInputKey)
 */
export function getMlFeatureFields(): StandardFieldDefinition[] {
  return STANDARD_FIELDS.filter((f) => f.costingInputKey);
}

/**
 * Map standard field key to ML feature name
 */
export function getMLFeatureKey(fieldKey: string): string | undefined {
  const field = STANDARD_FIELDS.find((f) => f.key === fieldKey);
  return field?.costingInputKey;
}
