// api/src/lib/standardQuestionnaireFields.ts
/**
 * Standard questionnaire fields for ML training consistency
 * These fields are automatically created for all tenants and provide
 * a consistent feature set for the RandomForest price prediction model.
 * 
 * Updated based on joineryai_questionnaire_fields.csv requirements
 */

export type StandardFieldDefinition = {
  key: string;
  label: string;
  type: "TEXT" | "NUMBER" | "SELECT" | "BOOLEAN" | "TEXTAREA" | "DATE";
  options?: string[];
  required: boolean;
  costingInputKey?: string;
  helpText?: string;
  placeholder?: string;
  sortOrder: number;
  group?: string;
  scope: "project_details" | "public" | "manufacturing";
  isStandard: true;
};

/**
 * Standard fields organized by category
 * These map directly to ML model features and business processes
 */
export const STANDARD_FIELDS: StandardFieldDefinition[] = [
  // ============ PROJECT DETAILS (scope: project_details - lead/quote specific info) ============
  {
    key: "enquiry_number",
    label: "Enquiry Number",
    type: "TEXT",
    required: false,
    helpText: "Internal reference number",
    placeholder: "ENQ-2025-001",
    sortOrder: 150,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "delivery_address",
    label: "Delivery Address",
    type: "TEXT",
    required: false,
    helpText: "Delivery location if different from client address",
    placeholder: "123 Project Site, Town, Postcode",
    sortOrder: 151,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "project_description",
    label: "Project Description",
    type: "TEXTAREA",
    required: false,
    helpText: "Project background, requirements, constraints",
    placeholder: "Describe the project details...",
    sortOrder: 152,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "client_type",
    label: "What type of client are they?",
    type: "SELECT",
    options: ["Homeowner", "Trade/Builder", "Architect", "Developer", "Commercial", "Other"],
    required: false,
    helpText: "Client category for workflow routing",
    sortOrder: 153,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "jms_number",
    label: "JMS No",
    type: "TEXT",
    required: false,
    helpText: "Job Management System reference",
    placeholder: "JMS-123",
    sortOrder: 154,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "site_visit_required",
    label: "Site visit req?",
    type: "SELECT",
    options: ["Yes", "No", "Not sure"],
    required: false,
    helpText: "Does this project need a site survey?",
    sortOrder: 155,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "follow_up_notes",
    label: "Follow up notes",
    type: "TEXTAREA",
    required: false,
    helpText: "Internal follow-up reminders and actions",
    placeholder: "Next steps, callbacks, etc.",
    sortOrder: 156,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "quoted_by",
    label: "Quoted by",
    type: "TEXT",
    required: false,
    helpText: "Team member who prepared the quote",
    placeholder: "Staff name",
    sortOrder: 157,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "installation_location",
    label: "Where will this be",
    type: "TEXT",
    required: false,
    helpText: "Specific installation location details",
    placeholder: "Front of house, rear extension, etc.",
    sortOrder: 158,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },

  // ============ PUBLIC QUESTIONNAIRE (scope: public - customer-facing) ============
  {
    key: "glazing_type",
    label: "Glazing Type",
    type: "SELECT",
    options: ["Standard Double Glazing", "Triple Glazing", "Vacuum Glass", "Single Glazing", "None"],
    required: false,
    costingInputKey: "glazing_type",
    helpText: "Glass specification",
    sortOrder: 200,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "has_curves",
    label: "Curved or Arched Design",
    type: "BOOLEAN",
    required: false,
    costingInputKey: "has_curves",
    helpText: "Includes curved or arched elements",
    sortOrder: 201,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "window_style",
    label: "Window Style",
    type: "SELECT",
    options: ["Casement", "Sash", "Tilt & Turn", "Fixed", "Bay", "Other"],
    required: false,
    helpText: "Window opening style",
    sortOrder: 202,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "door_type",
    label: "Door Type",
    type: "SELECT",
    options: ["External Front Door", "Internal Door", "Bifold Doors", "French Doors", "Sliding Doors", "Stable Door"],
    required: false,
    costingInputKey: "door_type",
    helpText: "Primary door type",
    sortOrder: 203,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "timber_type",
    label: "Timber Type",
    type: "SELECT",
    options: ["Oak", "Accoya", "Iroko", "Sapele", "Pine", "Engineered", "Other"],
    required: false,
    costingInputKey: "timber_type",
    helpText: "Wood species",
    sortOrder: 204,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "finish",
    label: "Finish",
    type: "SELECT",
    options: ["Factory Painted", "Factory Stained", "Primed Only", "Bare Wood"],
    required: false,
    costingInputKey: "finish",
    helpText: "Surface finish",
    sortOrder: 205,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "ironmongery_level",
    label: "Ironmongery Level",
    type: "SELECT",
    options: ["Standard", "Enhanced", "Heritage"],
    required: false,
    costingInputKey: "ironmongery_level",
    helpText: "Quality / complexity of ironmongery",
    sortOrder: 206,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "ironmongery_description",
    label: "Ironmongery Description",
    type: "TEXTAREA",
    required: false,
    helpText: "Specific ironmongery requirements",
    placeholder: "e.g., Brass handles, security locks...",
    sortOrder: 207,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "quantity",
    label: "Quantity",
    type: "NUMBER",
    required: false,
    costingInputKey: "quantity",
    helpText: "Total count of identical items",
    placeholder: "e.g., 2",
    sortOrder: 208,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "preferred_installation_date",
    label: "Preferred Installation Date",
    type: "DATE",
    required: false,
    helpText: "When would you like installation?",
    sortOrder: 209,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "project_description",
    label: "Project Description",
    type: "TEXTAREA",
    required: false,
    helpText: "Brief description of what you need",
    placeholder: "Tell us about your project...",
    sortOrder: 210,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "height_mm",
    label: "Height (mm)",
    type: "NUMBER",
    required: false,
    costingInputKey: "height_mm",
    helpText: "Height in millimeters",
    placeholder: "e.g., 2100",
    sortOrder: 211,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "width_mm",
    label: "Width (mm)",
    type: "NUMBER",
    required: false,
    costingInputKey: "width_mm",
    helpText: "Width in millimeters",
    placeholder: "e.g., 900",
    sortOrder: 212,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },
  {
    key: "glazing_bars",
    label: "Glazing Bars",
    type: "BOOLEAN",
    required: false,
    costingInputKey: "glazing_bars",
    helpText: "Include glazing bars in windows/doors",
    sortOrder: 213,
    group: "Public Questionnaire",
    scope: "public",
    isStandard: true,
  },

  // Additional project details fields merged from old internal scope
  {
    key: "area_m2",
    label: "Project Area (m²)",
    type: "NUMBER",
    required: false,
    costingInputKey: "area_m2",
    helpText: "Computed automatically from dimensions",
    sortOrder: 159,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "project_type",
    label: "Project Type",
    type: "SELECT",
    options: ["Windows", "Doors", "French Doors", "Bifold Doors", "Sash Windows", "Staircase", "Kitchen", "Wardrobes", "Alcove Units", "Other"],
    required: false,
    costingInputKey: "project_type",
    helpText: "Set by tenant – internal classification",
    sortOrder: 160,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "date_quote_sent",
    label: "Date Quote Sent",
    type: "DATE",
    required: false,
    helpText: "Auto-populated when quote sent",
    sortOrder: 161,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "date_of_enquiry",
    label: "Date of Enquiry",
    type: "DATE",
    required: false,
    helpText: "Auto-populated when lead created",
    sortOrder: 162,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "quote_ref",
    label: "Quote ref",
    type: "TEXT",
    required: false,
    helpText: "Internal reference number",
    placeholder: "e.g., Q-2025-001",
    sortOrder: 163,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "quote_value",
    label: "Quote Value",
    type: "NUMBER",
    required: false,
    helpText: "Total quoted amount",
    sortOrder: 164,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "source",
    label: "Source",
    type: "SELECT",
    options: ["Website", "Phone", "Email", "Walk-in", "Referral", "Trade", "Other"],
    required: false,
    helpText: "Lead origin channel",
    sortOrder: 165,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "timber",
    label: "Timber",
    type: "SELECT",
    options: ["Oak", "Accoya", "Iroko", "Sapele", "Pine", "Engineered", "Mixed", "Other"],
    required: false,
    helpText: "Timber specification for internal tracking",
    sortOrder: 166,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },
  {
    key: "date_order_placed",
    label: "Date Order Placed",
    type: "DATE",
    required: false,
    helpText: "Auto-populated when opportunity won",
    sortOrder: 167,
    group: "Project Details",
    scope: "project_details",
    isStandard: true,
  },

  // ============ MANUFACTURING (scope: manufacturing - post-won production) ============
  {
    key: "production_notes",
    label: "Production Notes",
    type: "TEXTAREA",
    required: false,
    helpText: "Special instructions for manufacturing",
    placeholder: "Any specific details for workshop...",
    sortOrder: 400,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "manufacturing_start_date",
    label: "Manufacturing Start Date",
    type: "DATE",
    required: false,
    helpText: "When manufacturing/production begins",
    sortOrder: 401,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "manufacturing_end_date",
    label: "Manufacturing End Date",
    type: "DATE",
    required: false,
    helpText: "When manufacturing/production completes",
    sortOrder: 402,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "installation_start_date",
    label: "Installation Start Date",
    type: "DATE",
    required: false,
    helpText: "When installation begins",
    sortOrder: 403,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "installation_end_date",
    label: "Installation End Date",
    type: "DATE",
    required: false,
    helpText: "When installation completes",
    sortOrder: 404,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  // Material tracking - Timber
  {
    key: "timber_ordered",
    label: "Timber - Ordered",
    type: "DATE",
    required: false,
    helpText: "Date timber was ordered",
    sortOrder: 405,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "timber_expected",
    label: "Timber - Expected",
    type: "DATE",
    required: false,
    helpText: "Expected timber delivery date",
    sortOrder: 406,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "timber_received",
    label: "Timber - Received",
    type: "DATE",
    required: false,
    helpText: "Date timber was received",
    sortOrder: 407,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  // Material tracking - Glass
  {
    key: "glass_ordered",
    label: "Glass - Ordered",
    type: "DATE",
    required: false,
    helpText: "Date glass was ordered",
    sortOrder: 408,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "glass_expected",
    label: "Glass - Expected",
    type: "DATE",
    required: false,
    helpText: "Expected glass delivery date",
    sortOrder: 409,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "glass_received",
    label: "Glass - Received",
    type: "DATE",
    required: false,
    helpText: "Date glass was received",
    sortOrder: 410,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  // Material tracking - Ironmongery
  {
    key: "ironmongery_ordered",
    label: "Ironmongery - Ordered",
    type: "DATE",
    required: false,
    helpText: "Date ironmongery was ordered",
    sortOrder: 411,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "ironmongery_expected",
    label: "Ironmongery - Expected",
    type: "DATE",
    required: false,
    helpText: "Expected ironmongery delivery date",
    sortOrder: 412,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "ironmongery_received",
    label: "Ironmongery - Received",
    type: "DATE",
    required: false,
    helpText: "Date ironmongery was received",
    sortOrder: 413,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  // Material tracking - Paint
  {
    key: "paint_ordered",
    label: "Paint - Ordered",
    type: "DATE",
    required: false,
    helpText: "Date paint was ordered",
    sortOrder: 414,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "paint_expected",
    label: "Paint - Expected",
    type: "DATE",
    required: false,
    helpText: "Expected paint delivery date",
    sortOrder: 415,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "paint_received",
    label: "Paint - Received",
    type: "DATE",
    required: false,
    helpText: "Date paint was received",
    sortOrder: 416,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  // Production planning
  {
    key: "projected_hours",
    label: "Projected Hours",
    type: "NUMBER",
    required: false,
    helpText: "Estimated production time",
    placeholder: "e.g., 40",
    sortOrder: 417,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "signed_off_date",
    label: "Signed Off Date",
    type: "DATE",
    required: false,
    helpText: "Date work was approved/completed",
    sortOrder: 418,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
  {
    key: "fensa_registration",
    label: "FENSA Registration",
    type: "BOOLEAN",
    required: false,
    helpText: "FENSA certification required",
    sortOrder: 419,
    group: "Manufacturing",
    scope: "manufacturing",
    isStandard: true,
  },
];

/**
 * Get fields by group for conditional rendering
 */
export function getFieldsByGroup(group: string): StandardFieldDefinition[] {
  return STANDARD_FIELDS.filter((f) => f.group === group);
}

/**
 * Get all unique groups in display order
 */
export function getFieldGroups(): string[] {
  const groups = [...new Set(STANDARD_FIELDS.map((f) => f.group).filter(Boolean))];
  const order = ["Project Details", "Public Questionnaire", "Manufacturing"];
  return order.filter((g) => groups.includes(g));
}

/**
 * Get fields by scope for context-specific rendering
 */
export function getFieldsByScope(scope: "project_details" | "public" | "manufacturing"): StandardFieldDefinition[] {
  return STANDARD_FIELDS.filter((f) => f.scope === scope);
}

/**
 * Get fields that map to ML features (have costingInputKey)
 */
export function getMlFeatureFields(): StandardFieldDefinition[] {
  return STANDARD_FIELDS.filter((f) => f.costingInputKey);
}

/**
 * Map standard field key to ML feature name
 */
export function getMLFeatureKey(fieldKey: string): string | undefined {
  const field = STANDARD_FIELDS.find((f) => f.key === fieldKey);
  return field?.costingInputKey;
}
