'use client';

import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import { Edit, Trash2, Copy, Box, Search, Filter } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useToast } from '@/components/ui/use-toast';

interface ComponentProfile {
  id: string;
  profileType: string;
  dimensions: {
    widthMm: number;
    depthMm: number;
  };
  geometry: {
    svg?: string;
    type?: string;
  };
}

interface ComponentLookup {
  id: string;
  code: string;
  name: string;
  description?: string;
  componentType: string;
  productTypes: string[];
  basePrice: number;
  profile?: ComponentProfile;
  metadata?: {
    widthMm?: number;
    depthMm?: number;
    autoGenerated?: boolean;
  };
  supplierId?: string;
  supplier?: {
    name: string;
  };
}

export function ComponentLibrarySection() {
  const [components, setComponents] = useState<ComponentLookup[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState<string | null>(null);
  const [selectedComponent, setSelectedComponent] = useState<ComponentLookup | null>(null);
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [assignOptionCode, setAssignOptionCode] = useState<string>('');
  const [assignDialogOpen, setAssignDialogOpen] = useState(false);
  const [productOptions, setProductOptions] = useState<Array<{ id: string; label: string; category: string; type: string }>>([]);
  const [pickerCategory, setPickerCategory] = useState<string>('all');
  const [pickerSearch, setPickerSearch] = useState<string>('');
  const { toast } = useToast();

  useEffect(() => {
    loadComponents();
    loadProductOptions();
  }, []);

  const loadComponents = async () => {
    try {
      setLoading(true);
      const response = await fetch('/api/components', {
        credentials: 'include',
      });
      if (!response.ok) throw new Error('Failed to load components');
      const data = await response.json();
      setComponents(data);
    } catch (error) {
      console.error('Failed to load component library:', error);
    } finally {
      setLoading(false);
    }
  };

  const loadProductOptions = async () => {
    try {
      const res = await fetch('/api/tenant/settings', { credentials: 'include' });
      if (!res.ok) return;
      const data = await res.json();
      const out: Array<{ id: string; label: string; category: string; type: string }> = [];
      (data.productTypes || []).forEach((cat: any) => {
        (cat.types || []).forEach((t: any) => {
          (t.options || []).forEach((opt: any) => {
            out.push({ id: opt.id, label: opt.label, category: cat.id, type: t.type });
          });
        });
      });
      setProductOptions(out);
    } catch (err) {
      console.error('Failed to load product options', err);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Delete this component? Products using it may be affected.')) return;
    
    try {
      const response = await fetch(`/api/components/${id}`, {
        method: 'DELETE',
        credentials: 'include',
      });
      if (!response.ok) throw new Error('Failed to delete component');
      await loadComponents();
    } catch (error) {
      console.error('Failed to delete component:', error);
      alert('Failed to delete component');
    }
  };

  const handleDuplicate = async (component: ComponentLookup) => {
    try {
      const response = await fetch('/api/components', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          ...component,
          id: undefined,
          code: `${component.code}_COPY`,
          name: `${component.name} (Copy)`,
        }),
      });
      if (!response.ok) throw new Error('Failed to duplicate component');
      await loadComponents();
    } catch (error) {
      console.error('Failed to duplicate component:', error);
      alert('Failed to duplicate component');
    }
  };

  // Filter and search
  const filteredComponents = components.filter(comp => {
    const matchesSearch = searchTerm === '' || 
      comp.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      comp.code.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesType = !filterType || comp.componentType === filterType;
    
    return matchesSearch && matchesType;
  });

  const componentTypes = Array.from(new Set(components.map(c => c.componentType)));

  if (loading) {
    return (
      <div className="space-y-4">
        <h3 className="text-lg font-medium">Component Library</h3>
        <div className="text-sm text-muted-foreground">Loading components...</div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-medium">Component Library</h3>
          <p className="text-sm text-muted-foreground">
            Reusable components with profiles. Update a component to affect all products using it.
          </p>
        </div>
        <Button variant="outline" size="sm">
          <Box className="w-4 h-4 mr-2" />
          Import Components
        </Button>
      </div>

      {/* Search and Filter */}
      <div className="flex gap-3">
        <div className="flex-1 relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input
            placeholder="Search components..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-9"
          />
        </div>
        <div className="flex gap-2">
          <Button
            variant={filterType === null ? 'default' : 'outline'}
            size="sm"
            onClick={() => setFilterType(null)}
          >
            All
          </Button>
          {componentTypes.map(type => (
            <Button
              key={type}
              variant={filterType === type ? 'default' : 'outline'}
              size="sm"
              onClick={() => setFilterType(type)}
            >
              {type}
            </Button>
          ))}
        </div>
      </div>

      {/* Components Table */}
      <div className="border rounded-lg">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Code</TableHead>
              <TableHead>Name</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Profile</TableHead>
              <TableHead>Used In</TableHead>
              <TableHead>Price</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredComponents.length === 0 && (
              <TableRow>
                <TableCell colSpan={7} className="text-center text-muted-foreground py-8">
                  No components found. Use AI Estimation to generate components automatically.
                </TableCell>
              </TableRow>
            )}
            {filteredComponents.map(comp => (
              <TableRow key={comp.id}>
                <TableCell className="font-mono text-xs">{comp.code}</TableCell>
                <TableCell>
                  <div className="flex items-center gap-2">
                    {comp.name}
                    {comp.metadata?.autoGenerated && (
                      <Badge variant="secondary" className="text-xs">AI</Badge>
                    )}
                  </div>
                </TableCell>
                <TableCell>
                  <Badge variant="outline">{comp.componentType}</Badge>
                </TableCell>
                <TableCell>
                  {comp.profile && (
                    <div className="flex items-center gap-2">
                      {comp.profile.geometry?.svg && (
                        <div 
                          className="w-8 h-8 border rounded"
                          dangerouslySetInnerHTML={{ 
                            __html: comp.profile.geometry.svg 
                          }}
                        />
                      )}
                      <span className="text-xs text-muted-foreground">
                        {comp.metadata?.widthMm}×{comp.metadata?.depthMm}mm
                      </span>
                    </div>
                  )}
                </TableCell>
                <TableCell>
                  <div className="flex flex-wrap gap-1">
                    {comp.productTypes.map(pt => (
                      <Badge key={pt} variant="secondary" className="text-xs">
                        {pt}
                      </Badge>
                    ))}
                  </div>
                </TableCell>
                <TableCell>£{comp.basePrice.toFixed(2)}</TableCell>
                <TableCell className="text-right">
                  <div className="flex justify-end gap-1">
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-8 w-8 p-0"
                      onClick={() => {
                        setSelectedComponent(comp);
                        setEditDialogOpen(true);
                      }}
                    >
                      <Edit className="w-4 h-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-8 w-8 p-0"
                      onClick={() => handleDelete(comp.id)}
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      className="h-8 px-2"
                      onClick={() => { setSelectedComponent(comp); setAssignDialogOpen(true); }}
                    >
                      Assign
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-8 w-8 p-0 text-destructive"
                      onClick={() => handleDelete(comp.id)}
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      {/* Edit Dialog */}
      <Dialog open={editDialogOpen} onOpenChange={setEditDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Edit Component</DialogTitle>
            <DialogDescription>
              Changes will affect all products using this component
            </DialogDescription>
          </DialogHeader>
          {selectedComponent && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label>Code</Label>
                  <Input value={selectedComponent.code} disabled />
                </div>
                <div>
                  <Label>Type</Label>
                  <Input value={selectedComponent.componentType} disabled />
                </div>
              </div>
              <div>
                <Label>Name</Label>
                <Input 
                  value={selectedComponent.name}
                  onChange={(e) => setSelectedComponent({
                    ...selectedComponent,
                    name: e.target.value
                  })}
                />
              </div>
              <div>
                <Label>Description</Label>
                <Input 
                  value={selectedComponent.description || ''}
                  onChange={(e) => setSelectedComponent({
                    ...selectedComponent,
                    description: e.target.value
                  })}
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label>Width (mm)</Label>
                  <Input 
                    type="number"
                    value={selectedComponent.metadata?.widthMm || ''}
                    onChange={(e) => setSelectedComponent({
                      ...selectedComponent,
                      metadata: {
                        ...selectedComponent.metadata,
                        widthMm: parseFloat(e.target.value)
                      }
                    })}
                  />
                </div>
                <div>
                  <Label>Depth (mm)</Label>
                  <Input 
                    type="number"
                    value={selectedComponent.metadata?.depthMm || ''}
                    onChange={(e) => setSelectedComponent({
                      ...selectedComponent,
                      metadata: {
                        ...selectedComponent.metadata,
                        depthMm: parseFloat(e.target.value)
                      }
                    })}
                  />
                </div>
              </div>
              <div>
                <Label>Base Price (£)</Label>
                <Input 
                  type="number"
                  step="0.01"
                  value={selectedComponent.basePrice}
                  onChange={(e) => setSelectedComponent({
                    ...selectedComponent,
                    basePrice: parseFloat(e.target.value)
                  })}
                />
              </div>
              {selectedComponent.profile?.geometry?.svg && (
                <div>
                  <Label>Profile Preview</Label>
                  <div 
                    className="border rounded-lg p-4 bg-muted/50"
                    style={{ width: '200px', height: '200px' }}
                    dangerouslySetInnerHTML={{ 
                      __html: selectedComponent.profile.geometry.svg 
                    }}
                  />
                </div>
              )}
              {/* Usage and assignment */}
              <div className="border rounded-lg p-3 bg-slate-50">
                <div className="text-xs font-medium text-slate-700 mb-1">Used in product options</div>
                <div className="flex flex-wrap gap-1 mb-2">
                  {(selectedComponent.productTypes || []).map((pt) => (
                    <Badge key={pt} variant="secondary" className="text-xs">{pt}</Badge>
                  ))}
                  {(!selectedComponent.productTypes || selectedComponent.productTypes.length === 0) && (
                    <div className="text-xs text-muted-foreground">None</div>
                  )}
                </div>
                <div className="flex items-center gap-2">
                  <Input
                    placeholder="Add to product option (e.g., entrance-single)"
                    value={assignOptionCode}
                    onChange={(e) => setAssignOptionCode(e.target.value)}
                  />
                  <Button
                    variant="outline"
                    onClick={async () => {
                      if (!selectedComponent || !assignOptionCode.trim()) return;
                      try {
                        const current = Array.isArray(selectedComponent.productTypes) ? selectedComponent.productTypes : [];
                        if (current.includes(assignOptionCode.trim())) return;
                        const next = [...current, assignOptionCode.trim()];
                        const response = await fetch(`/api/components/${encodeURIComponent(selectedComponent.id)}`, {
                          method: 'PUT',
                          headers: { 'Content-Type': 'application/json' },
                          credentials: 'include',
                          body: JSON.stringify({ productTypes: next })
                        });
                        if (!response.ok) throw new Error('Failed to assign');
                        setAssignOptionCode('');
                        // Update local state and refresh list
                        setSelectedComponent({ ...selectedComponent, productTypes: next });
                        await loadComponents();
                      } catch (err) {
                        console.error('Assign failed', err);
                        alert('Failed to assign to product option');
                      }
                    }}
                  >
                    Add
                  </Button>
                </div>
              </div>
              <div className="flex justify-end gap-2 pt-4">
                <Button variant="outline" onClick={() => setEditDialogOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={async () => {
                  try {
                    const response = await fetch(`/api/components/${selectedComponent.id}`, {
                      method: 'PATCH',
                      headers: { 'Content-Type': 'application/json' },
                      credentials: 'include',
                      body: JSON.stringify(selectedComponent),
                    });
                    if (!response.ok) throw new Error('Failed to update component');
                    await loadComponents();
                    setEditDialogOpen(false);
                  } catch (error) {
                    console.error('Failed to update component:', error);
                    alert('Failed to update component');
                  }
                }}>
                  Save Changes
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Assign to Product Option Dialog */}
      <Dialog open={assignDialogOpen} onOpenChange={setAssignDialogOpen}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>Assign to Product Option</DialogTitle>
            <DialogDescription>
              Link this component to a product option so it appears in that template.
            </DialogDescription>
          </DialogHeader>
          {selectedComponent ? (
            <div className="space-y-3">
              <div className="text-sm">Component: <span className="font-mono">{selectedComponent.code}</span> — {selectedComponent.name}</div>
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <Label>Filter by Category</Label>
                  <Select value={pickerCategory} onValueChange={setPickerCategory}>
                    <SelectTrigger>
                      <SelectValue placeholder="All" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All</SelectItem>
                      {[...new Set(productOptions.map((p) => p.category))].map((cat) => (
                        <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label>Search</Label>
                  <Input value={pickerSearch} onChange={(e) => setPickerSearch(e.target.value)} placeholder="Search options" />
                </div>
              </div>
              <div className="max-h-64 overflow-auto border rounded">
                {productOptions
                  .filter((p) => pickerCategory === 'all' || p.category === pickerCategory)
                  .filter((p) => !pickerSearch.trim() || (p.label + ' ' + p.id).toLowerCase().includes(pickerSearch.toLowerCase()))
                  .map((p) => (
                    <div key={p.id} className="flex items-center justify-between px-3 py-2 border-b last:border-b-0">
                      <div className="text-sm">
                        <span className="font-medium">{p.label}</span>
                        <span className="ml-2 text-xs text-slate-600">[{p.category} / {p.type}]</span>
                        <span className="ml-2 text-xs font-mono text-slate-500">{p.id}</span>
                      </div>
                      <Button size="sm" onClick={async () => {
                        try {
                          const current = Array.isArray(selectedComponent.productTypes) ? selectedComponent.productTypes : [];
                          if (current.includes(p.id)) {
                            toast({ title: 'Already assigned', description: `${selectedComponent.code} is already linked to ${p.id}` });
                            return;
                          }
                          const next = [...current, p.id];
                          const response = await fetch(`/api/components/${encodeURIComponent(selectedComponent.id)}`, {
                            method: 'PUT',
                            headers: { 'Content-Type': 'application/json' },
                            credentials: 'include',
                            body: JSON.stringify({ productTypes: next })
                          });
                          if (!response.ok) throw new Error('Failed to assign');
                          toast({ title: 'Assigned', description: `Linked ${selectedComponent.code} to ${p.id}` });
                          setSelectedComponent({ ...selectedComponent, productTypes: next });
                        } catch (err: any) {
                          toast({ title: 'Assign failed', description: err?.message || 'Could not assign', variant: 'destructive' });
                        }
                      }}>Link</Button>
                    </div>
                  ))}
              </div>
              <div className="flex justify-end">
                <Button variant="outline" onClick={() => setAssignDialogOpen(false)}>Close</Button>
              </div>
            </div>
          ) : null}
        </DialogContent>
      </Dialog>
    </div>
  );
}
