'use client';

import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import { Edit, Trash2, Copy, Box, Search, Filter } from 'lucide-react';

interface ComponentProfile {
  id: string;
  profileType: string;
  dimensions: {
    widthMm: number;
    depthMm: number;
  };
  geometry: {
    svg?: string;
    type?: string;
  };
}

interface ComponentLookup {
  id: string;
  code: string;
  name: string;
  description?: string;
  componentType: string;
  productTypes: string[];
  basePrice: number;
  profile?: ComponentProfile;
  metadata?: {
    widthMm?: number;
    depthMm?: number;
    autoGenerated?: boolean;
  };
  supplierId?: string;
  supplier?: {
    name: string;
  };
}

export function ComponentLibrarySection() {
  const [components, setComponents] = useState<ComponentLookup[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState<string | null>(null);
  const [selectedComponent, setSelectedComponent] = useState<ComponentLookup | null>(null);
  const [editDialogOpen, setEditDialogOpen] = useState(false);

  useEffect(() => {
    loadComponents();
  }, []);

  const loadComponents = async () => {
    try {
      setLoading(true);
      const response = await fetch('/api/components', {
        credentials: 'include',
      });
      if (!response.ok) throw new Error('Failed to load components');
      const data = await response.json();
      setComponents(data);
    } catch (error) {
      console.error('Failed to load component library:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Delete this component? Products using it may be affected.')) return;
    
    try {
      const response = await fetch(`/api/components/${id}`, {
        method: 'DELETE',
        credentials: 'include',
      });
      if (!response.ok) throw new Error('Failed to delete component');
      await loadComponents();
    } catch (error) {
      console.error('Failed to delete component:', error);
      alert('Failed to delete component');
    }
  };

  const handleDuplicate = async (component: ComponentLookup) => {
    try {
      const response = await fetch('/api/components', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          ...component,
          id: undefined,
          code: `${component.code}_COPY`,
          name: `${component.name} (Copy)`,
        }),
      });
      if (!response.ok) throw new Error('Failed to duplicate component');
      await loadComponents();
    } catch (error) {
      console.error('Failed to duplicate component:', error);
      alert('Failed to duplicate component');
    }
  };

  // Filter and search
  const filteredComponents = components.filter(comp => {
    const matchesSearch = searchTerm === '' || 
      comp.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      comp.code.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesType = !filterType || comp.componentType === filterType;
    
    return matchesSearch && matchesType;
  });

  const componentTypes = Array.from(new Set(components.map(c => c.componentType)));

  if (loading) {
    return (
      <div className="space-y-4">
        <h3 className="text-lg font-medium">Component Library</h3>
        <div className="text-sm text-muted-foreground">Loading components...</div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-medium">Component Library</h3>
          <p className="text-sm text-muted-foreground">
            Reusable components with profiles. Update a component to affect all products using it.
          </p>
        </div>
        <Button variant="outline" size="sm">
          <Box className="w-4 h-4 mr-2" />
          Import Components
        </Button>
      </div>

      {/* Search and Filter */}
      <div className="flex gap-3">
        <div className="flex-1 relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input
            placeholder="Search components..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-9"
          />
        </div>
        <div className="flex gap-2">
          <Button
            variant={filterType === null ? 'default' : 'outline'}
            size="sm"
            onClick={() => setFilterType(null)}
          >
            All
          </Button>
          {componentTypes.map(type => (
            <Button
              key={type}
              variant={filterType === type ? 'default' : 'outline'}
              size="sm"
              onClick={() => setFilterType(type)}
            >
              {type}
            </Button>
          ))}
        </div>
      </div>

      {/* Components Table */}
      <div className="border rounded-lg">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Code</TableHead>
              <TableHead>Name</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Profile</TableHead>
              <TableHead>Used In</TableHead>
              <TableHead>Price</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredComponents.length === 0 && (
              <TableRow>
                <TableCell colSpan={7} className="text-center text-muted-foreground py-8">
                  No components found. Use AI Estimation to generate components automatically.
                </TableCell>
              </TableRow>
            )}
            {filteredComponents.map(comp => (
              <TableRow key={comp.id}>
                <TableCell className="font-mono text-xs">{comp.code}</TableCell>
                <TableCell>
                  <div className="flex items-center gap-2">
                    {comp.name}
                    {comp.metadata?.autoGenerated && (
                      <Badge variant="secondary" className="text-xs">AI</Badge>
                    )}
                  </div>
                </TableCell>
                <TableCell>
                  <Badge variant="outline">{comp.componentType}</Badge>
                </TableCell>
                <TableCell>
                  {comp.profile && (
                    <div className="flex items-center gap-2">
                      {comp.profile.geometry?.svg && (
                        <div 
                          className="w-8 h-8 border rounded"
                          dangerouslySetInnerHTML={{ 
                            __html: comp.profile.geometry.svg 
                          }}
                        />
                      )}
                      <span className="text-xs text-muted-foreground">
                        {comp.metadata?.widthMm}×{comp.metadata?.depthMm}mm
                      </span>
                    </div>
                  )}
                </TableCell>
                <TableCell>
                  <div className="flex flex-wrap gap-1">
                    {comp.productTypes.map(pt => (
                      <Badge key={pt} variant="secondary" className="text-xs">
                        {pt}
                      </Badge>
                    ))}
                  </div>
                </TableCell>
                <TableCell>£{comp.basePrice.toFixed(2)}</TableCell>
                <TableCell className="text-right">
                  <div className="flex justify-end gap-1">
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-8 w-8 p-0"
                      onClick={() => {
                        setSelectedComponent(comp);
                        setEditDialogOpen(true);
                      }}
                    >
                      <Edit className="w-4 h-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-8 w-8 p-0"
                      onClick={() => handleDuplicate(comp)}
                    >
                      <Copy className="w-4 h-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-8 w-8 p-0 text-destructive"
                      onClick={() => handleDelete(comp.id)}
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      {/* Edit Dialog */}
      <Dialog open={editDialogOpen} onOpenChange={setEditDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Edit Component</DialogTitle>
            <DialogDescription>
              Changes will affect all products using this component
            </DialogDescription>
          </DialogHeader>
          {selectedComponent && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label>Code</Label>
                  <Input value={selectedComponent.code} disabled />
                </div>
                <div>
                  <Label>Type</Label>
                  <Input value={selectedComponent.componentType} disabled />
                </div>
              </div>
              <div>
                <Label>Name</Label>
                <Input 
                  value={selectedComponent.name}
                  onChange={(e) => setSelectedComponent({
                    ...selectedComponent,
                    name: e.target.value
                  })}
                />
              </div>
              <div>
                <Label>Description</Label>
                <Input 
                  value={selectedComponent.description || ''}
                  onChange={(e) => setSelectedComponent({
                    ...selectedComponent,
                    description: e.target.value
                  })}
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label>Width (mm)</Label>
                  <Input 
                    type="number"
                    value={selectedComponent.metadata?.widthMm || ''}
                    onChange={(e) => setSelectedComponent({
                      ...selectedComponent,
                      metadata: {
                        ...selectedComponent.metadata,
                        widthMm: parseFloat(e.target.value)
                      }
                    })}
                  />
                </div>
                <div>
                  <Label>Depth (mm)</Label>
                  <Input 
                    type="number"
                    value={selectedComponent.metadata?.depthMm || ''}
                    onChange={(e) => setSelectedComponent({
                      ...selectedComponent,
                      metadata: {
                        ...selectedComponent.metadata,
                        depthMm: parseFloat(e.target.value)
                      }
                    })}
                  />
                </div>
              </div>
              <div>
                <Label>Base Price (£)</Label>
                <Input 
                  type="number"
                  step="0.01"
                  value={selectedComponent.basePrice}
                  onChange={(e) => setSelectedComponent({
                    ...selectedComponent,
                    basePrice: parseFloat(e.target.value)
                  })}
                />
              </div>
              {selectedComponent.profile?.geometry?.svg && (
                <div>
                  <Label>Profile Preview</Label>
                  <div 
                    className="border rounded-lg p-4 bg-muted/50"
                    style={{ width: '200px', height: '200px' }}
                    dangerouslySetInnerHTML={{ 
                      __html: selectedComponent.profile.geometry.svg 
                    }}
                  />
                </div>
              )}
              <div className="flex justify-end gap-2 pt-4">
                <Button variant="outline" onClick={() => setEditDialogOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={async () => {
                  try {
                    const response = await fetch(`/api/components/${selectedComponent.id}`, {
                      method: 'PATCH',
                      headers: { 'Content-Type': 'application/json' },
                      credentials: 'include',
                      body: JSON.stringify(selectedComponent),
                    });
                    if (!response.ok) throw new Error('Failed to update component');
                    await loadComponents();
                    setEditDialogOpen(false);
                  } catch (error) {
                    console.error('Failed to update component:', error);
                    alert('Failed to update component');
                  }
                }}>
                  Save Changes
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
