#!/bin/bash
# api/scripts/migrate-local.sh
# Safe local migration helper for Prisma schema changes
# Usage: ./scripts/migrate-local.sh "add_new_table"

set -e

MIGRATION_NAME="$1"
if [ -z "$MIGRATION_NAME" ]; then
  echo "Usage: $0 <migration_name>"
  echo "Example: $0 add_analytics_events"
  exit 1
fi

# Load local env
if [ -f .env.local ]; then
  set -a
  source .env.local
  set +a
fi

# Verify DATABASE_URL is local
if [[ ! "$DATABASE_URL" =~ localhost|127\.0\.0\.1 ]]; then
  echo "❌ ERROR: DATABASE_URL must point to localhost"
  echo "Current: $DATABASE_URL"
  exit 1
fi

echo "🔍 Using database: $DATABASE_URL"

# Create migration folder
TIMESTAMP=$(date -u +%Y%m%d%H%M%S)
MIGRATION_DIR="prisma/migrations/${TIMESTAMP}_${MIGRATION_NAME}"
mkdir -p "$MIGRATION_DIR"
echo "📁 Created: $MIGRATION_DIR"

# Try to generate migration SQL (may fail due to shadow DB)
echo "📝 Attempting to generate migration SQL..."
if pnpm prisma migrate dev --name "$MIGRATION_NAME" --create-only 2>/dev/null; then
  echo "✅ Migration SQL generated by Prisma"
  MIGRATION_FILE="$MIGRATION_DIR/migration.sql"
else
  echo "⚠️  Prisma migrate dev failed (expected due to shadow DB issues)"
  echo "📝 You need to manually write migration.sql"
  
  # Create template
  MIGRATION_FILE="$MIGRATION_DIR/migration.sql"
  cat > "$MIGRATION_FILE" << 'EOF'
-- Manual migration
-- Add your DDL statements here

-- Example:
-- CREATE TABLE "NewModel" (
--   "id" TEXT NOT NULL,
--   "tenantId" TEXT NOT NULL,
--   "field" TEXT,
--   "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   CONSTRAINT "NewModel_pkey" PRIMARY KEY ("id")
-- );
--
-- CREATE INDEX "NewModel_tenantId_idx" ON "NewModel"("tenantId");
--
-- ALTER TABLE "NewModel"
--   ADD CONSTRAINT "NewModel_tenantId_fkey"
--   FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id")
--   ON DELETE CASCADE ON UPDATE CASCADE;
EOF
  
  echo ""
  echo "📄 Template created at: $MIGRATION_FILE"
  echo "✏️  Edit this file with your migration SQL, then run:"
  echo ""
  echo "   psql \"\$DATABASE_URL\" -f $MIGRATION_FILE"
  echo "   pnpm prisma generate"
  echo ""
  exit 0
fi

# Apply migration
echo "🚀 Applying migration to local database..."
psql "$DATABASE_URL" -f "$MIGRATION_FILE"

# Regenerate Prisma client
echo "🔄 Regenerating Prisma client..."
pnpm prisma generate

# Verify
echo "✅ Migration applied successfully!"
echo ""
echo "📋 Next steps:"
echo "   1. Test your changes"
echo "   2. git add $MIGRATION_DIR"
echo "   3. git commit -m 'feat: $MIGRATION_NAME'"
echo ""
echo "📦 For production deployment:"
echo "   psql \"\$PROD_DATABASE_URL\" -f $MIGRATION_FILE"
echo "   npx prisma migrate resolve --applied ${TIMESTAMP}_${MIGRATION_NAME}"
echo ""
