ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "estimatedValue" DECIMAL;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "quotedValue" DECIMAL;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "dateQuoteSent" TIMESTAMP(3);
