import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Upload, FileText, Loader2, X } from "lucide-react";
import { useRef } from "react";

type ClientQuoteFile = {
  id: string;
  name?: string | null;
  sizeBytes?: number | null;
  uploadedAt?: string | null;
};

type ClientQuoteUploadCardProps = {
  files?: ClientQuoteFile[];
  onUpload?: (files: FileList) => void;
  onOpen?: (file: ClientQuoteFile) => void;
  onDelete?: (file: ClientQuoteFile) => void;
  isUploading?: boolean;
};

export function ClientQuoteUploadCard({
  files = [],
  onUpload,
  onOpen,
  onDelete,
  isUploading,
}: ClientQuoteUploadCardProps) {
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFiles = e.target.files;
    if (selectedFiles && selectedFiles.length > 0 && onUpload) {
      onUpload(selectedFiles);
    }
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  return (
    <Card className="shadow-sm">
      <CardHeader className="pb-4">
        <div className="flex items-start justify-between">
          <div>
            <CardTitle className="text-lg">Client quote PDFs</CardTitle>
            <p className="mt-1 text-sm text-muted-foreground">
              Upload quotes from JoinerySoft or similar software
            </p>
          </div>
          <Button
            size="sm"
            variant="outline"
            onClick={() => fileInputRef.current?.click()}
            disabled={isUploading}
            className="gap-2"
          >
            {isUploading ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Uploading...
              </>
            ) : (
              <>
                <Upload className="h-4 w-4" />
                Upload
              </>
            )}
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <input
          ref={fileInputRef}
          type="file"
          accept="application/pdf"
          multiple
          hidden
          onChange={handleFileSelect}
        />

        {files.length === 0 ? (
          <div className="flex flex-col items-center justify-center rounded-xl border-2 border-dashed border-muted-foreground/20 bg-muted/20 p-8 text-center">
            <FileText className="h-12 w-12 text-muted-foreground/40 mb-3" />
            <p className="text-sm font-medium text-muted-foreground mb-1">
              No client quotes uploaded yet
            </p>
            <p className="text-xs text-muted-foreground/70">
              Upload PDF quotes generated by your estimating software
            </p>
          </div>
        ) : (
          <div className="space-y-2">
            {files.map((file) => (
              <div
                key={file.id}
                className="flex items-center justify-between rounded-lg border bg-card p-3 hover:bg-muted/30 transition-colors"
              >
                <button
                  onClick={() => onOpen?.(file)}
                  className="flex items-center gap-3 flex-1 min-w-0 text-left"
                >
                  <FileText className="h-5 w-5 text-blue-600 flex-shrink-0" />
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-foreground truncate">
                      {file.name || "Client quote"}
                    </p>
                    <div className="flex items-center gap-2 text-xs text-muted-foreground mt-0.5">
                      {file.sizeBytes && (
                        <span>{formatBytes(file.sizeBytes)}</span>
                      )}
                      {file.uploadedAt && (
                        <>
                          {file.sizeBytes && <span>•</span>}
                          <span>
                            Uploaded {new Date(file.uploadedAt).toLocaleDateString()}
                          </span>
                        </>
                      )}
                    </div>
                  </div>
                </button>
                {onDelete && (
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={(e) => {
                      e.stopPropagation();
                      onDelete(file);
                    }}
                    className="h-8 w-8 p-0 text-muted-foreground hover:text-destructive"
                  >
                    <X className="h-4 w-4" />
                  </Button>
                )}
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function formatBytes(bytes: number): string {
  if (bytes === 0) return "0 B";
  const k = 1024;
  const sizes = ["B", "KB", "MB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + " " + sizes[i];
}
